<?php
$arrData = Mage::registry('guestData');
?>
<div id="syncproduct_tabs_form_section_content"><div class="entry-edit">
        <div class="content-header">
            <h3 class="icon-head head-adminhtml-syncproduct">Guest Connection Setup</h3>
            <p class="form-buttons"><button style="" onclick="credentialsForm.submit();" class="scalable save" type="button" id="id_81d3377e908884e6e85315cdb272b4f7"><span>Save Data</span></button></p>
        </div>

        <div class="entry-edit">
            <form method="post" action="<?php echo $this->getUrl('*/*/guestsetup');?>" id="credentials_form" name="credentials_form"><div><input type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey()?>" name="form_key"></div>
                <div style="" id="syncproduct_tabs_form_section_content"><div class="entry-edit">
                        <div class="entry-edit-head">
                            <h4 class="icon-head head-edit-form fieldset-legend">Magento-iBright Guest Credentials</h4>
                            <div class="form-buttons"></div>
                        </div>
                        <div id="syncproduct_form" class="fieldset ">
                            <div class="hor-scroll">
                                <table cellspacing="0" class="form-list">
                                    <tbody>
                                        <tr>
                                            <td class="label"><label for="ibrightguesturl">iBright Server <span class="required">*</span></label></td>
                                            <td class="value">
                                                <input type="text" style="width:450px;" class="required-entry input-text required-entry" title="iBright Server" name="ibrightguesturl" id="ibrightguesturl" value="<?php echo $arrData['ibright_guest_url']; ?>" />
											</td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label for="ibrightguestuser">User <span class="required">*</span></label></td>
                                            <td class="value">
                                                <input type="text" style="width:150px;" class="required-entry input-text required-entry" title="User" name="ibrightguestuser" id="ibrightguestuser" value="<?php echo ($arrData['ibright_guest_login'])?$arrData['ibright_guest_login']:'anonymous'; ?>" />
											</td>
                                        </tr>
                                        <tr style="display:none;">
                                            <td class="label"><label for="ibrightguestpassword">Password <span class="required">*</span></label></td>
                                            <td class="value">
                                                <input type="password" style="width:150px;" class="required-entry input-text required-entry" title="Password" name="ibrightguestpassword" id="ibrightguestpassword" value="<?php echo ($arrData['ibright_guest_password'])?base64_decode($arrData['ibright_guest_password']):'password'; ?>" />
											</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
    credentialsForm = new varienForm('credentials_form', '');
</script>