<?php
/**
 * Product view template
 * Web@print
 *
 */
?>
<?php $_ibrightDetails = Mage::helper('syncproduct')->designToolDetails();?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct();?>


<script type="text/javascript">
	var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
    $jq = jQuery.noConflict();
    window.onload = responseUrl();
    
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
            <div class="product-shop">
                <div class="product-name">
                    <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                </div>
                <?php
                   $isPrintProduct = $_product->getResource()->getAttribute('print_product')->getFrontend()->getValue($_product);
                   if($isPrintProduct == 'Yes'){
                ?>
                <?php if($_product->isSaleable()): ?>
				
                <div style="padding:10px 0px;">
                    <?php if(strpos($_product->getProductUrl(), "?"))
						$returnPdtUrl = $_product->getProductUrl()."&";
					else
						$returnPdtUrl = $_product->getProductUrl()."?";
					$pdtUrl = urlencode($returnPdtUrl);?>

					<!-- Create XML for logged in users...-->
					<?php if(Mage::getSingleton('customer/session')->isLoggedIn()){
						$userEmail = Mage::getSingleton('customer/session')->getCustomer()->getEmail();
						$userXml = urlencode('<?xml version="1.0" encoding="UTF-8"?><ticket id="magento"><user uid="'.$userEmail.'"></user></ticket>');
					}?>

                    <button type="button" title="Individualize Template" <?php if(!Mage::getSingleton('customer/session')->isLoggedIn()) { ?> onclick="javascript:showBox();" <?php } else { ?> onclick="GB_showCenter('Design Your Template', '<?php echo $_ibrightDetails->getIbrightFrontendUrl();?>?xml=<?php echo $userXml?>&timestamp=<?php echo urlencode(date('Y m d h:i:s'))?>&code=<?php echo urlencode('magentoclx')?>&forwardAfterLogin=individualize&templateId=<?php echo $_product->getTemplateId()?>&shopid=<?php echo Mage::getSingleton('customer/session')->getCustomer()->getId()?>&backurl=<?php echo $pdtUrl?>', 950, 950);" <?php } ?> class="button button-orange btn-cart"><span><span><?php echo $this->__('Design Tool') ?></span></span></button>
                </div>
                <?php endif; ?>
                <?php }?>
                <!--<h2><a href="/uploaddesign">You can also upload your own design</a></h2>-->

                <?php if ($this->canEmailToFriend()): ?>
                <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
                <?php endif; ?>
                <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                <?php echo $this->getChildHtml('alert_urls') ?>
                <?php echo $this->getChildHtml('product_type_data') ?>
                <?php echo $this->getTierPriceHtml() ?>
                <?php echo $this->getChildHtml('extrahint') ?>

                <?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                            <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                    <span class="or"><?php echo $this->__('OR') ?></span>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addto') ?>
                </div>
                <?php endif; ?>

                <?php if ($_product->getShortDescription()):?>
                <div class="short-description">
                    <h2><?php echo $this->__('Quick Overview') ?></h2>
                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                </div>
                <?php endif;?>

                <?php echo $this->getChildHtml('other');?>
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>

            </div>

            <div class="product-img-box">
                <?php echo $this->getChildHtml('media') ?>
            </div>

            <div class="clearer"></div>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>
        </form>
        <script type="text/javascript">
            //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                        form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
            //]]>

            //function for dropdown box
            function showBox() {
                document.getElementById("backgroundPopup").style.display = "block";
                document.getElementById("copyTemplateFormContainer").style.display = "block";
                document.getElementById("copyTemplateForm").style.display = "block";
                //$("#copyTemplateForm").slideDown("fast");

            }
            function closeBox()
            {
                document.getElementById("backgroundPopup").style.display = "none";
                document.getElementById("copyTemplateFormContainer").style.display = "none";
                document.getElementById("copyTemplateForm").style.display = "none";
                //$("#copyTemplateForm").slideUp("fast");

            }
        </script>
    </div>

    <div class="product-collateral">
        <?php echo $this->getChildHtml('info_tabs') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
    </div>
</div>
<!--Pop Up Section -->
<div id="copyTemplateFormContainer" style="border:1px solid #fff;display:none">
    <?php Mage::getSingleton('customer/session')->setBeforeAuthUrl($_product->getProductUrl());?>
    <div id="copyTemplateForm"  class="form-holder">
        <div class="panel-heading">
            <h2><?php echo $this->__('Your design and save your pictures')?> !</h2>
        </div>
        <form action="" name="addCopyTemplateForm" id="addCopyTemplateForm" method="post">
            <ul>
                <li><a href="javascript:closeBox();" class="copyTemplate"></a></li>
                <li>
                    <?php echo $this->__('To save your design and your pictures, we create an account for you. So you can view your pictures and designs at any time even further edit and send friends.'); ?>
                </li>
                <li style="height:30px;">&nbsp;</li>
                <li><button type="button" title="Login" onclick="window.location.href='/customer/account/login'" class="button btn-cart"><span><span><?php echo $this->__('login')?></span></span></button>&nbsp;<button type="button" title="Registration " onclick="window.location.href='/customer/account/create'" class="button btn-cart" style="padding-left:40px;"><span><span><?php echo $this->__('registration')?></span></span></button>&nbsp;
                    <?php if(strpos($_product->getProductUrl(), "?"))
						$returnPdtUrl = $_product->getProductUrl()."&";
					else
						$returnPdtUrl = $_product->getProductUrl()."?";
					$pdtUrl = urlencode($returnPdtUrl);?>
					<?php $_ibrightGuestDetails = Mage::helper('syncproduct')->guestDesignToolDetails(); ?>
					<button type="button" title="Login" onclick="GB_showCenter('Design Your Template', '<?php echo $_ibrightGuestDetails->getIbrightGuestUrl();?>?login=<?php echo $_ibrightGuestDetails->getIbrightGuestLogin()?>&forwardAfterLogin=individualize&templateId=<?php echo $_product->getTemplateId()?>&shopid=&backurl=<?php echo utf8_encode($pdtUrl)?>', 950, 950); closeBox();" class="button btn-cart" style="padding-left:40px;"><span><span><?php echo $this->__('continue as a guest');?></span></span></button>
                </li>
                <li>&nbsp;</li>
                <li style="text-align:right; font-size:10px;"><span>(<?php echo $this->__('no data is stored'); ?>)</span>&nbsp;&nbsp;</li>

            </ul>
        </form>
    </div>

</div>
<div id="backgroundPopup"></div>
<!-- end -->
